requirements:
  - title: 1. You are product based
    description: I thrive when collaborating with teams that prioritize product development. Crafting solutions and driving product vision aligns with my passion and strengths.
  - title: 2. Rails Enthusiasts
    description: A significant portion of my expertise lies in working with Rails. Partnering with fellow Rails enthusiasts ensures a shared language and a deeper understanding of the ecosystem.
  - title: 3. Holistic Development Involvement
    description: I firmly believe that developers bring more to the table than just code. I value environments where developers are involved in the entire feature-building process, providing insights from design to deployment.
  - title: 4. Efficient Communication
    description: While I appreciate the value of communication, I believe in its quality over quantity. Teams that forgo daily meetings in favor of focused, meaningful discussions resonate with me, allowing for deeper work and creativity.